### ISSUE TITLE
Test with maps

### ISSUE THREAD

**Issue by LysanderGG** [KazuCocoa/ex_parametarized#22]
Hi !

It seems that the macro `test_with_params` is not usable with more than one map.

The following test passes.
```
  test_with_params "with map value", fn a ->
    assert a.b == 1
    assert a.c == 2
  end do
    [
      {%{b: 1, c: 2}}
    ]
  end
```
The following test fails with the error below:
```
  test_with_params "with map value", fn a ->
    assert a.b == 1
    assert a.c == 2
  end do
    [
      {%{b: 1, c: 2}},
      {%{b: 1, c: 2}}
    ]
  end
```
Error:
```
** (CompileError) test/ex_parameterized_test.exs: invalid quoted expression: %{b: 1, c: 2}
```

Is this intended behavior?
I think this is pretty limiting and makes `test_with_params` unusable with maps.

I am missing something?

Thank you!

**Comment by KazuCocoa** [comment]
It will be fixed with https://hex.pm/packages/ex_parameterized/1.3.2 . Thanks!
@LysanderGG

**Comment by LysanderGG** [comment]
Thank you for the super quick fix!
It works without problem for more complex maps too :ok_hand:
