### ISSUE TITLE
Enum.map of maps doesn't work

### ISSUE THREAD

**Issue by LysanderGG** [KazuCocoa/ex_parametarized#24]
Hi again,

With 1.3.2, direct maps work without problem, but maps from Enum.map don't work.
I think it would be great to have this too, what do you think?

Example of test that gives a CompileError:
```
test_with_params "ast from enum of maps", fn a ->
    assert a == %{b: 1, c: 2}
  end do
    Enum.map([{%{b: 1, c: 2}}], fn x -> x end)
  end
```

Here is the CompileError I get:
```
(CompileError) test/ex_parameterized_test.exs: invalid quoted expression: %{b: 1, c: 2}
```

**Comment by KazuCocoa** [comment]
https://hex.pm/packages/ex_parameterized/1.3.3
