### ISSUE TITLE
Multiple params with atom and map fails

### ISSUE THREAD

**Issue by MiyamotoAkira** [KazuCocoa/ex_parametarized#27]
The following code
```elixir
test_with_params "something", fn the_atom, the_map ->
# Some code
end do
  [
    {:L, %{a: 1, b: 2, c: 3}}
  ]
end
```
fails with
```
** (BadArityError) #Function<0.3029121/2 in MarsroverTest."test 'something': 'L': number of 0"/1> with arity 2 called with 3 arguments ({:a, 1}, {:b, 2}, {:c, 3})
```

If I break the map and pass as four individual parameters it works.
```elixir
 {:L, 1, 2, 3}
```

If I transform the atom into a string so that
```elixir
test_with_params "something", fn the_atom, the_map ->
  # Some code
  String.to_atom(the_atom)
end do
  [
    {"L", %{a: 1, b: 2, c: 3}}
  ]
end
```

then there is a compile error
```
** (CompileError) test/something_test.exs: invalid quoted expression: %{a: 1, b: 2, c: 3}
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    test/something_test.exs:102: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by MiyamotoAkira** [comment]
Looking at the code, because of the decision to pass the description as an atom, the first element of my tuple cannot be an atom on itself. Is that correct? Due to the use of atoms in Elixir, it seems like a strange decision to me (I can work around it). That explains my initial issue.

The second problem can be solved if instead of that just passing to `run` a direct `Tuple.to_list(values)` we escape first all maps on the list (based on https://elixir-lang.org/getting-started/meta/quote-and-unquote.html), so something like:

```elixir
  defp test_with(desc, fun, {values, num}) do
    escaped = Tuple.to_list(values)
    |> Enum.map(fn x ->
      case x do
        value when is_map(value) -> Macro.escape(x)
        _ -> x
      end
    end)

    run("'#{desc}': number of #{num}", fun, escaped)
  end
```

Seems to work (all current tests pass on my fork of the library, plus the one that I added to test my issues). I will create an initial PR with that code (extracting the `escape` functionality, as it can be applied at least in two places).

**Comment by KazuCocoa** [comment]
~~In this library, the `:L` part is expected as message for the parameters.~~ So, I'd expect it as string.

```
{:L, %{a: 1, b: 2, c: 3}}
```

~~So, I'd close this issue with supporting below format.~~

```
{"L", %{a: 1, b: 2, c: 3}}
```

update.

**Comment by KazuCocoa** [comment]
https://hexdocs.pm/ex_parameterized/1.3.5/api-reference.html
